### ISSUE TITLE
Set up the initial project code

### ISSUE THREAD

**Issue by chrisbendel** [CSI-280/team1#1]
This is the largest chunk of work, so I want at least 3 people to work on this, so that you are all on the same page with the tech choice you make and how to interact with the code base (adding files, running the app, etc)

Feel free to use basic HTML/CSS/JS or any JS framework of your choice (React, Angular, Vue, etc...)

This should be the first issue to get done, as any other work will be dependent on this.

**Comment by JakeCapra** [comment]
Pushed starter code to master

**Comment by ikemike87** [comment]
@JakeCapra Hey so I pulled the git and I tried to run the react app, but it wouldn't start. I made a react app earlier in the week because I'm doing #3. It seems the node_modules folder isn't in the repo and I also needed to use the command _npm install react-router-dom_. This got the react app to start. Let me know if you are able to start the react app from just whats in the repo now.

**Comment by JakeCapra** [comment]
@ikemike87 Sorry, I'll upload the modules now. I'm using the react-router to change between pages within the site.

**Comment by JakeCapra** [comment]
Ok, so I figured out that the node_modules folder actually has a .gitignore, and that its best to install your own modules. You can do this with `npm install`. https://stackoverflow.com/questions/52818492/pushing-create-react-app-to-github-node-modules-folder-has-not-been-copied

**Comment by ikemike87** [comment]
Ok, that makes sense
